version: "3.8"
services:
  # --- Frontend (Vite Dev mit Hot-Reload) ---
  frontend:
    image: node:20-alpine
    container_name: outfit-frontend
    working_dir: /app
    environment:
      - NODE_ENV=development
      # WICHTIG: Browser muss das Backend über localhost erreichen
      - VITE_API_BASE_URL=http://localhost:8000
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    # installiert deps & startet dev-server
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0" 
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    image: outfit-backend:latest
    container_name: outfit-backend
    environment:
      - PYTHONUNBUFFERED=1
      - COMFY_URL=http://comfyui:8188
      # Gemeinsame Pfade (Host-Ordner) für Uploads & Ergebnisse
      - INPUT_DIR=/shared/input
      - OUTPUT_DIR=/shared/output
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app                    # dein Backend-Code
      - ./ComfyUI/input:/shared/input     # geteilter Input-Ordner (Host)
      - ./ComfyUI/output:/shared/output   # geteilter Output-Ordner (Host)
    entrypoint: ["sh","-c","trap 'echo Backend stopped' EXIT && uvicorn main:app --host 0.0.0.0 --port 8000"]
    depends_on:
      - comfyui
    restart: unless-stopped

  comfyui:
    build:
      context: ./ComfyUI
    image: comfyui:latest
    container_name: comfyui
    ports:
      - "8188:8188"
    volumes:
      - ./ComfyUI/models:/app/models
      - ./ComfyUI/input:/app/input
      - ./ComfyUI/output:/app/output
      - ./ComfyUI/workflows:/app/workflows
    restart: "no"
    environment:
      - CUDA_VISIBLE_DEVICES="".  # CUDA komplett deaktivieren
    command: python main.py --cpu --disable-xformers --listen --port 8188




