version: "3.8"

services:

  backend:
    build:
      context: ./backend
    image: outfit-backend:latest
    container_name: outfit-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  # Nur Backend-Code mounten, falls nötig
    restart: "no"
    entrypoint: ["sh", "-c", "trap 'echo Backend stopped' EXIT && uvicorn main:app --host 0.0.0.0 --port 8000"]

  comfyui:
    build:
      context: ./ComfyUI
    image: comfyui:latest
    container_name: comfyui
    ports:
      - "8188:8188"
    volumes:
      - ./ComfyUI/models:/app/models
      - ./ComfyUI/input:/app/input
      - ./ComfyUI/output:/app/output
    restart: "no"
    environment:
      - CUDA_VISIBLE_DEVICES=""
